#!/usr/python/bin/python3
# -*- coding:utf-8 -*-
############################
#File Name: merge_pdf.py
#Author: ykyk
#Mail: 525178992@qq.com
#Created Time: 2019-01-05 16:04:19
############################

from PyPDF2 import PdfFileMerger

merger = PdfFileMerger()

input1 = open('document1.pdf', 'rb')
input2 = open('document2.pdf', 'rb')
input3 = open('document3.pdf', 'rb')

merger.append(fileobj = input1, pages = (0,3))
merger.merge(position = 2, fileobj = input2, pages = (0,1))
merger.append(input3)

output = open('document-output.pdf', 'wb')
merger.write(output)
